# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7390491037930ed495892bf47b45d215"
name = "task-03"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_discounts,read_discounts"

[discount.metafields.app.function-configuration]
type = "json"
name = "Function configuration"
description = "JSON settings for the discount Function"

  [discount.metafields.app.function-configuration.access]
  admin = "merchant_read_write"

[product.metafields.custom.warranty_days]
type = "number_integer"
name = "Warranty days"
description = "Number of warranty days for this product"

  [product.metafields.custom.warranty_days.access]
  admin = "merchant_read_write"
  storefront = "public_read"


[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
