# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

api_version = "2026-07"

[[extensions]]
name = "title-block"
handle = "title-block"
type = "ui_extension"
uid = "9a6cc1ec-6121-cb46-22d3-f11590af6f223880e27f"

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true

[[extensions.metafields]]
namespace = "$app:custom"
key = "warranty_days"

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Text displayed in checkout. If empty, the app uses \"Default title\"."

[[extensions.settings.fields]]
key = "add_button"
type = "single_line_text_field"
name = "Add button text"
description = "If empty, the app uses \"Add to cart\"."

[[extensions.settings.fields]]
key = "variant"
type = "variant_reference"
name = "Product variant"
